[package]
name = "tdf_wl"
version = "0.1.0"
edition = "2018"

[workspace]
members = [
    "eve-data-core",
    "eve-data-macros",
]

[dependencies]
eve_data_macros = { path = "./eve-data-macros" }
eve_data_core = { path = "./eve-data-core" }

sqlx = { version = "0.8.6", features = ["runtime-tokio-native-tls", "macros", "chrono", "postgres"] }
rocket = { version = "0.5.1", features = ["json"] }
lazy_static = "1"
chrono = "0.4"
# reqwest = { version = "*", default-features = false, features = ["json", "rustls-tls"] }
reqwest = { version = "*", features = ["json", "form"] }
tokio = { version = "*", features = ["time"] }

serde = { version = "1", features = ["derive"] }
serde_json = "*"
rmp-serde = "*"
yaml-merge-keys = { version = "*", features = ["serde_yaml"] }
serde_yaml = "*"
toml = "*"
branca = "0.10"
hex = "0.4"
regex = "*"
rand = "*"
thiserror = "*"

jsonwebtoken = {version = "8", default-features = false }

# [features]
# default = ["sqlite"]
# mysql = ["sqlx/mysql"]
# sqlite = ["sqlx/sqlite"]

[profile.dev.package.sqlx-macros]
opt-level = 3
